# Generated by Django 2.2.5 on 2019-09-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='item_name',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
