# Generated by Django 2.2.5 on 2019-09-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shipments_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='arriving_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
